### ISSUE TITLE
Sundial Scheduler failed to initialize: Unexpected problem: No resource for MyJob

### ISSUE THREAD

**Issue by mbuechner** [timmolter/dropwizard-sundial#17]
I'm getting the following and I really have no idea what I am doing wrong. Double-checked everything, made a very simple example based on your README.md - it's always the same problem! :-(

```
INFO  [2017-11-15 16:20:59,562] org.eclipse.jetty.server.Server: jetty-9.4.7.v20170914
INFO  [2017-11-15 16:20:59,574] org.knowm.sundial.ee.SundialInitializerListener: Sundial Initializer Servlet loaded, initializing Scheduler...
INFO  [2017-11-15 16:20:59,587] org.quartz.core.SchedulerSignalerImpl: Initialized Scheduler Signaler of type: class org.quartz.core.SchedulerSignalerImpl
INFO  [2017-11-15 16:20:59,590] org.quartz.core.RAMJobStore: RAMJobStore initialized.
INFO  [2017-11-15 16:20:59,590] org.quartz.plugins.xml.XMLSchedulingDataProcessorPlugin: Initializing XMLSchedulingDataProcessorPlugin Plug-in.
INFO  [2017-11-15 16:20:59,590] org.quartz.plugins.management.ShutdownHookPlugin: Registering Quartz shutdown hook.
INFO  [2017-11-15 16:20:59,590] org.knowm.sundial.plugins.AnnotationJobTriggerPlugin: Initializing AnnotationJobTriggerPlugin Plug-in.
INFO  [2017-11-15 16:20:59,612] org.quartz.plugins.xml.XMLSchedulingDataProcessor: Parsing XML file: jobs.xml
INFO  [2017-11-15 16:20:59,694] org.quartz.plugins.xml.XMLSchedulingDataProcessor: Adding 1 jobs, 1 triggers.
INFO  [2017-11-15 16:20:59,694] org.quartz.plugins.xml.XMLSchedulingDataProcessor: Scheduled job: name: 'MyJob', Job Class: de.ddb.jobs.MyJob, description: null isConcurrencyAllowed: false, jobDataMap: [MyParam=42] 
INFO  [2017-11-15 16:20:59,694] org.quartz.plugins.xml.XMLSchedulingDataProcessor: Scheduled trigger: Trigger 'MyJob-Trigger',  triggerClass: CronTriggerImpl, jobName: MyJob, jobDataMap: empty, calendar: null, misfireInstruction: 0, priority: 5, nextFireTime: null, cronEx: 0/45 * * * * ?, timeZone: Europe/Berlin
INFO  [2017-11-15 16:20:59,696] org.knowm.sundial.plugins.AnnotationJobTriggerPlugin: Loading annotated jobs from de.ddb.jobs.MyJob.
ERROR [2017-11-15 16:20:59,698] org.knowm.sundial.ee.SundialInitializerListener: Sundial Scheduler failed to initialize: 
! java.lang.RuntimeException: Unexpected problem: No resource for de/ddb/jobs/MyJob
! at org.quartz.classloading.CascadingClassLoadHelper.getJobClasses(CascadingClassLoadHelper.java:227)
! at org.knowm.sundial.plugins.AnnotationJobTriggerPlugin.start(AnnotationJobTriggerPlugin.java:88)
! at org.quartz.QuartzScheduler.startPlugins(QuartzScheduler.java:1113)
! at org.quartz.QuartzScheduler.start(QuartzScheduler.java:211)
! at org.knowm.sundial.ee.SundialInitializerListener.contextInitialized(SundialInitializerListener.java:122)
! at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:890)
! at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:532)
! at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:853)
! at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:344)
! at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:785)
! at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:261)
! at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
! at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:131)
! at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:105)
! at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
! at com.codahale.metrics.jetty9.InstrumentedHandler.doStart(InstrumentedHandler.java:103)
! at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
! at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:131)
! at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:113)
! at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
! at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
! at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:131)
! at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:105)
! at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
! at org.eclipse.jetty.server.handler.gzip.GzipHandler.doStart(GzipHandler.java:273)
! at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
! at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:131)
! at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:105)
! at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
! at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
! at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:131)
! at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:105)
! at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
! at org.eclipse.jetty.server.handler.StatisticsHandler.doStart(StatisticsHandler.java:252)
! at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
! at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:131)
! at org.eclipse.jetty.server.Server.start(Server.java:449)
! at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:105)
! at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
! at org.eclipse.jetty.server.Server.doStart(Server.java:416)
! at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
! at io.dropwizard.cli.ServerCommand.run(ServerCommand.java:53)
! at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:44)
! at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:85)
! at io.dropwizard.cli.Cli.run(Cli.java:75)
! at io.dropwizard.Application.run(Application.java:93)
! at de.ddb.MyApplication.main(MyApplication.java:27)
```
I am using Version 1.2.0.

**Comment by timmolter** [comment]
It's tough to say for sure why it's not working, but fundamentally it should be fine. Take a look at: <https://github.com/timmolter/XDropWizard> and see if you can spot a difference.

**Comment by mbuechner** [comment]
It was a misconfiguration in my YAML file:

- **Wrong:** `annotated-jobs-package-name: de.ddb.jobs.MyJob`
- **Correct:** `annotated-jobs-package-name: de.ddb.jobs`

Sorry! \*blush\*
